#!/usr/bin/env python3

import argparse
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT
    / "Sources"
    / "SwiftTUI"
    / "Runtime"
    / "Text"
    / "UnicodeLineBreakDataText.swift"
)


def parse_line_break(path: Path):
    ranges = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue

        code_range, class_name = [part.strip() for part in line.split(";")]
        if ".." in code_range:
            lower, upper = [int(part, 16) for part in code_range.split("..")]
        else:
            lower = upper = int(code_range, 16)
        ranges.append((lower, upper, class_name))

    ranges.sort()
    return ranges


def emit(output: Path, ranges):
    lines = [
        "# Generated by Scripts/generate-unicode-line-break-data.py.",
        "# Source: https://www.unicode.org/Public/17.0.0/ucd/LineBreak.txt",
    ]

    for lower, upper, class_name in ranges:
        lines.append(f"{lower:X}\t{upper:X}\t{class_name}")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join(
            [
                "// Generated by Scripts/generate-unicode-line-break-data.py.",
                "// Source: https://www.unicode.org/Public/17.0.0/ucd/LineBreak.txt",
                "",
                "extension UnicodeLineBreakClass {",
                '    static let lineBreakDataText = #"""',
                *lines,
                '"""#',
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path, nargs="?", default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()

    emit(arguments.output, parse_line_break(arguments.input))


if __name__ == "__main__":
    main()
