#!/usr/bin/env python3

import argparse
from pathlib import Path


CLASS_NAMES = {
    "AI": "ambiguous",
    "AK": "aksara",
    "AL": "alphabetic",
    "AP": "aksaraPrebase",
    "AS": "aksaraStart",
    "B2": "breakBoth",
    "BA": "breakAfter",
    "BB": "breakBefore",
    "BK": "mandatoryBreak",
    "CB": "contingentBreak",
    "CJ": "conditionalJapaneseStarter",
    "CL": "closePunctuation",
    "CM": "combiningMark",
    "CP": "closeParenthesis",
    "CR": "carriageReturn",
    "EB": "emojiBase",
    "EM": "emojiModifier",
    "EX": "exclamation",
    "GL": "glue",
    "H2": "hangulLv",
    "H3": "hangulLvt",
    "HH": "unambiguousHyphen",
    "HL": "hebrewLetter",
    "HY": "hyphen",
    "ID": "ideographic",
    "IN": "inseparable",
    "IS": "infixNumeric",
    "JL": "hangulLJamo",
    "JT": "hangulTJamo",
    "JV": "hangulVJamo",
    "LF": "lineFeed",
    "NL": "nextLine",
    "NS": "nonstarter",
    "NU": "numeric",
    "OP": "openPunctuation",
    "PO": "postfixNumeric",
    "PR": "prefixNumeric",
    "QU": "quotation",
    "RI": "regionalIndicator",
    "SA": "complexContext",
    "SG": "surrogate",
    "SP": "space",
    "SY": "breakSymbols",
    "VF": "viramaFinal",
    "VI": "virama",
    "WJ": "wordJoiner",
    "XX": "unknown",
    "ZW": "zeroWidthSpace",
    "ZWJ": "zeroWidthJoiner",
}


def parse_line_break(path: Path):
    ranges = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue

        code_range, class_name = [part.strip() for part in line.split(";")]
        if ".." in code_range:
            lower, upper = [int(part, 16) for part in code_range.split("..")]
        else:
            lower = upper = int(code_range, 16)
        ranges.append((lower, upper, class_name))

    ranges.sort()
    return ranges


def emit(output: Path, ranges):
    lines = [
        "// Generated by Scripts/generate-unicode-line-break-data.py.",
        "// Source: https://www.unicode.org/Public/17.0.0/ucd/LineBreak.txt",
        "",
        "extension UnicodeLineBreakClass {",
        "",
        "    static func untailoredClass(for scalar: Unicode.Scalar) -> UnicodeLineBreakClass {",
        "        let value = scalar.value",
        "        var lowerBound = 0",
        "        var upperBound = lineBreakRanges.count",
        "",
        "        while lowerBound < upperBound {",
        "            let middle = (lowerBound + upperBound) / 2",
        "            let range = lineBreakRanges[middle]",
        "            if value < range.lowerBound {",
        "                upperBound = middle",
        "            }",
        "            else if value > range.upperBound {",
        "                lowerBound = middle + 1",
        "            }",
        "            else {",
        "                return range.lineBreakClass",
        "            }",
        "        }",
        "",
        "        return defaultClass(for: value)",
        "    }",
        "",
        "    private static func defaultClass(for value: UInt32) -> UnicodeLineBreakClass {",
        "        switch value {",
        "        case 0x3400...0x4DBF,",
        "             0x4E00...0x9FFF,",
        "             0xF900...0xFAFF,",
        "             0x20000...0x3FFFD,",
        "             0x1F000...0x1FAFF,",
        "             0x1FC00...0x1FFFD:",
        "            return .ideographic",
        "        case 0x20A0...0x20CF:",
        "            return .prefixNumeric",
        "        case 0x1F100...0x1F10A,",
        "             0x1F110...0x1F12F,",
        "             0x1F130...0x1F14F:",
        "            return .alphabetic",
        "        default:",
        "            return .unknown",
        "        }",
        "    }",
        "",
        "    private static let lineBreakRanges: [UnicodeLineBreakRange] = [",
    ]

    for lower, upper, class_name in ranges:
        swift_name = CLASS_NAMES[class_name]
        lines.append(
            "        UnicodeLineBreakRange("
            f"lowerBound: 0x{lower:X}, "
            f"upperBound: 0x{upper:X}, "
            f"lineBreakClass: .{swift_name}"
            "),"
        )

    lines.extend(
        [
            "    ]",
            "}",
            "",
        ]
    )

    output.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    arguments = parser.parse_args()

    emit(arguments.output, parse_line_break(arguments.input))


if __name__ == "__main__":
    main()
